// Generated by gencpp from file rosserial_r2p/Test.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_R2P_MESSAGE_TEST_H
#define ROSSERIAL_R2P_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <rosserial_r2p/TestRequest.h>
#include <rosserial_r2p/TestResponse.h>


namespace rosserial_r2p
{

struct Test
{

typedef TestRequest Request;
typedef TestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Test
} // namespace rosserial_r2p


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosserial_r2p::Test > {
  static const char* value()
  {
    return "c63e85f503b805d84df783e71c6bb0d2";
  }

  static const char* value(const ::rosserial_r2p::Test&) { return value(); }
};

template<>
struct DataType< ::rosserial_r2p::Test > {
  static const char* value()
  {
    return "rosserial_r2p/Test";
  }

  static const char* value(const ::rosserial_r2p::Test&) { return value(); }
};


// service_traits::MD5Sum< ::rosserial_r2p::TestRequest> should match 
// service_traits::MD5Sum< ::rosserial_r2p::Test > 
template<>
struct MD5Sum< ::rosserial_r2p::TestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_r2p::Test >::value();
  }
  static const char* value(const ::rosserial_r2p::TestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_r2p::TestRequest> should match 
// service_traits::DataType< ::rosserial_r2p::Test > 
template<>
struct DataType< ::rosserial_r2p::TestRequest>
{
  static const char* value()
  {
    return DataType< ::rosserial_r2p::Test >::value();
  }
  static const char* value(const ::rosserial_r2p::TestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosserial_r2p::TestResponse> should match 
// service_traits::MD5Sum< ::rosserial_r2p::Test > 
template<>
struct MD5Sum< ::rosserial_r2p::TestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_r2p::Test >::value();
  }
  static const char* value(const ::rosserial_r2p::TestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_r2p::TestResponse> should match 
// service_traits::DataType< ::rosserial_r2p::Test > 
template<>
struct DataType< ::rosserial_r2p::TestResponse>
{
  static const char* value()
  {
    return DataType< ::rosserial_r2p::Test >::value();
  }
  static const char* value(const ::rosserial_r2p::TestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSSERIAL_R2P_MESSAGE_TEST_H
