// Generated by gencpp from file r2p_msgs/Encoder.msg
// DO NOT EDIT!


#ifndef R2P_MSGS_MESSAGE_ENCODER_H
#define R2P_MSGS_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace r2p_msgs
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : delta(0.0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : delta(0.0)  {
    }



   typedef float _delta_type;
  _delta_type delta;




  typedef boost::shared_ptr< ::r2p_msgs::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r2p_msgs::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::r2p_msgs::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::r2p_msgs::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::r2p_msgs::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r2p_msgs::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r2p_msgs::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace r2p_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'r2p_msgs': ['/home/ubuntu/catkin_ws/src/r2p_msgs-master/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::r2p_msgs::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r2p_msgs::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r2p_msgs::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r2p_msgs::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r2p_msgs::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r2p_msgs::Encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r2p_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b808a22d9acab1efdc64ddcf9bf82dfc";
  }

  static const char* value(const ::r2p_msgs::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb808a22d9acab1efULL;
  static const uint64_t static_value2 = 0xdc64ddcf9bf82dfcULL;
};

template<class ContainerAllocator>
struct DataType< ::r2p_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r2p_msgs/Encoder";
  }

  static const char* value(const ::r2p_msgs::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r2p_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 delta\n\
";
  }

  static const char* value(const ::r2p_msgs::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r2p_msgs::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.delta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r2p_msgs::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r2p_msgs::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "delta: ";
    Printer<float>::stream(s, indent + "  ", v.delta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // R2P_MSGS_MESSAGE_ENCODER_H
