// Generated by gencpp from file r2p_msgs/Vector3_32.msg
// DO NOT EDIT!


#ifndef R2P_MSGS_MESSAGE_VECTOR3_32_H
#define R2P_MSGS_MESSAGE_VECTOR3_32_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace r2p_msgs
{
template <class ContainerAllocator>
struct Vector3_32_
{
  typedef Vector3_32_<ContainerAllocator> Type;

  Vector3_32_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  Vector3_32_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::r2p_msgs::Vector3_32_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r2p_msgs::Vector3_32_<ContainerAllocator> const> ConstPtr;

}; // struct Vector3_32_

typedef ::r2p_msgs::Vector3_32_<std::allocator<void> > Vector3_32;

typedef boost::shared_ptr< ::r2p_msgs::Vector3_32 > Vector3_32Ptr;
typedef boost::shared_ptr< ::r2p_msgs::Vector3_32 const> Vector3_32ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r2p_msgs::Vector3_32_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r2p_msgs::Vector3_32_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace r2p_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'r2p_msgs': ['/home/ubuntu/catkin_ws/src/r2p_msgs-master/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::r2p_msgs::Vector3_32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r2p_msgs::Vector3_32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r2p_msgs::Vector3_32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r2p_msgs::Vector3_32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r2p_msgs::Vector3_32_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r2p_msgs::Vector3_32_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r2p_msgs::Vector3_32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::r2p_msgs::Vector3_32_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::r2p_msgs::Vector3_32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r2p_msgs/Vector3_32";
  }

  static const char* value(const ::r2p_msgs::Vector3_32_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r2p_msgs::Vector3_32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This represents a vector in free space (32 bit variant). \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::r2p_msgs::Vector3_32_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r2p_msgs::Vector3_32_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Vector3_32_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r2p_msgs::Vector3_32_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r2p_msgs::Vector3_32_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // R2P_MSGS_MESSAGE_VECTOR3_32_H
